forrest_watch_pictures:
    resource: "@ForrestWatchBundle/Controller/PicturesController.php"
    type:     annotation

forrest_watch_pictures:
    resource: "@ForrestWatchBundle/Controller/PicturesController.php"
    type:     annotation

forrest_watch_questions:
    resource: "@ForrestWatchBundle/Controller/QuestionsController.php"
    type:     annotation

forrest_watch_pictures:
    resource: "@ForrestWatchBundle/Controller/PicturesController.php"
    type:     annotation

forrest_watch_pictures:
    resource: "@ForrestWatchBundle/Controller/PicturesController.php"
    type:     annotation

forrest_watch_pictures:
    resource: "@ForrestWatchBundle/Controller/PicturesController.php"
    type:     annotation

forrest_watch_questions:
    resource: "@ForrestWatchBundle/Controller/QuestionsController.php"
    type:     annotation

forrest_watch_questions:
    resource: "@ForrestWatchBundle/Controller/QuestionsController.php"
    type:     annotation

forrest_watch_questions:
    resource: "@ForrestWatchBundle/Controller/QuestionsController.php"
    type:     annotation

forrest_watch_questions:
    resource: "@ForrestWatchBundle/Controller/QuestionsController.php"
    type:     annotation

forrest_watch_environment:
    resource: "@ForrestWatchBundle/Controller/EnvironmentController.php"
    type:     annotation

forrest_watch_region:
    resource: "@ForrestWatchBundle/Controller/RegionController.php"
    type:     annotation

forrest_watch_region:
    resource: "@ForrestWatchBundle/Controller/RegionController.php"
    type:     annotation

forrest_watch_region:
    resource: "@ForrestWatchBundle/Controller/RegionController.php"
    type:     annotation

forrest_watch_species:
    resource: "@ForrestWatchBundle/Controller/SpeciesController.php"
    type:     annotation

forrest_watch_phylum:
    resource: "@ForrestWatchBundle/Controller/PhylumController.php"
    type:     annotation

forrest_watch_kingdom:
    resource: "@ForrestWatchBundle/Controller/KingdomController.php"
    type:     annotation

forrest_watch_kingdom:
    resource: "@ForrestWatchBundle/Controller/KingdomController.php"
    type:     annotation

forrest_watch_phylum:
    resource: "@ForrestWatchBundle/Controller/PhylumController.php"
    type:     annotation

framework_kingdom:
    resource: "@FrameworkBundle/Controller/KingdomController.php"
    type:     annotation

forrest_watch:
    resource: "@ForrestWatchBundle/Controller/"
    type:     annotation
    prefix:   /

