<?php

namespace ForrestWatchBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhylumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhylumRepository extends EntityRepository
{
}
