<?php

namespace ForrestWatchBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResponcesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponcesRepository extends EntityRepository
{
}
