<?php

namespace ForrestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * KingdomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KingdomRepository extends EntityRepository
{
}
