<?php

namespace ForrestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * KingDomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KingDomRepository extends EntityRepository
{
}
