<?php

namespace ForrestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Region_questRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Region_questRepository extends EntityRepository
{
}
