<?php

namespace ForrestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RespocesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RespocesRepository extends EntityRepository
{
}
