<?php

namespace ForrestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Species_questRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Species_questRepository extends EntityRepository
{
}
